content: https://github.com/hirenoble/api-final.git#master
static: https://github.com/hirenoble/api-final.git#master
staticRoot: /webroot
directoryIndex: index.html

strains:
  default:
    code: /io-solutions/default/https---github-com-hirenoble-api-final-git--master--
    content: https://github.com/hirenoble/api-final.git#master
    static: https://github.com/hirenoble/api-final.git#master
    staticRoot: /webroot
    directoryIndex: index.html
